version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db

